---
title: "Assignment 2"
author: "Ahalya.J"
date: "2023-08-08"
output: html_document
---


```{r}
#qns 1

set.seed(1)
x=rnorm(100,0,1) #rnorm(100,mean=0,sd=1)

#b
eps=rnorm(100,0,sqrt(0.25))

#c
y =-1+0.5*x+eps
length(y)


#betao=-1, beta1=0.5
```
```{r}
#d
plot(x,y)

```
```{r}
#e
FitC=lm(y~x)
FitC
summary(FitC)
```
```{r}
#f
plot(x,y)                                                                                         
abline(FitC,col="red",lty=1)
abline(-1,0.5,col="blue",lty=2)
legend("topleft",c("Fit","True"),
       col=c("red","blue"),lty=c(1,2))

```
```{r}
#qn 2
View(boston)
boston
```
```{r}
attach(Boston)
fit1=lm(crim~zn)
summary(fit1)
```
```{r}
fit2=lm(crim~indus)
fit2
summary(fit2)
```
```{r}
fit3=lm(crim~chas)
fit3
summary(fit3)
```
```{r}
fit4=lm(crim~chas)
fit4
summary(fit4)
```
```{r}
fit5=lm(crim~nox)
fit5
summary(fit5)
```
```{r}
fit6=lm(crim~rm)
fit6
summary(fit6)
```
```{r}
fit7=lm(crim~age)
fit7
summary(fit7)
```
```{r}
fit8=lm(crim~dis)
fit8
summary(fit8)
```
```{r}
fit9=lm(crim~rad)
fit9
summary(fit9)
```
```{r}
fit10=lm(crim~tax)
fit10
summary(fit10)
```
```{r}
fit11=lm(crim~ptratio)
fit11
summary(fit11)
```
```{r}
fit12=lm(crim~black)
fit12
summary(fit12)
```
```{r}
fit13=lm(crim~lstat)
fit13
summary(fit13)
```
```{r}
fit14=lm(crim~medv)
fit14
summary(fit14)
```
```{r}
attach(boston)
par(mfrow=c(2,2))
plot(zn,crim)
plot(dis,crim)
plot(nox,crim)
plot(rm,crim)
```

```{r}
fit15=lm(crim~.,boston)
fit15
summary(fit15)

```


